start ..\dasdcat -i L:\Programming\Hercules\mvs-tk5\dasd\tk5002.299 pascal.passamp/*:sca 1>ALLFILES1 2>allfiles2
..\dasdcat -i L:\Programming\Hercules\mvs-tk5\dasd\tk5002.299 pascal.passamp/ackerman:sca>ackerman.pas
..\dasdcat -i L:\Programming\Hercules\mvs-tk5\dasd\tk5002.299 pascal.passamp/compare:sca>compare.pas
..\dasdcat -i L:\Programming\Hercules\mvs-tk5\dasd\tk5002.299 pascal.passamp/compress:sca>compress.pas
..\dasdcat -i L:\Programming\Hercules\mvs-tk5\dasd\tk5002.299 pascal.passamp/ed:sca>ed.pas
..\dasdcat -i L:\Programming\Hercules\mvs-tk5\dasd\tk5002.299 pascal.passamp/eightqns:sca>eightqns.pas
..\dasdcat -i L:\Programming\Hercules\mvs-tk5\dasd\tk5002.299 pascal.passamp/expand:sca>expand.pas
..\dasdcat -i L:\Programming\Hercules\mvs-tk5\dasd\tk5002.299 pascal.passamp/fft:sca>fft.pas
..\dasdcat -i L:\Programming\Hercules\mvs-tk5\dasd\tk5002.299 pascal.passamp/gcircle:sca>gcircle.pas
..\dasdcat -i L:\Programming\Hercules\mvs-tk5\dasd\tk5002.299 pascal.passamp/inquire:sca>inquire.pas
..\dasdcat -i L:\Programming\Hercules\mvs-tk5\dasd\tk5002.299 pascal.passamp/invert:sca>invert.pas
..\dasdcat -i L:\Programming\Hercules\mvs-tk5\dasd\tk5002.299 pascal.passamp/pascref:sca>pascref.pas
..\dasdcat -i L:\Programming\Hercules\mvs-tk5\dasd\tk5002.299 pascal.passamp/pat:sca>pat.pas
..\dasdcat -i L:\Programming\Hercules\mvs-tk5\dasd\tk5002.299 pascal.passamp/patpas:sca>patpas.pas
..\dasdcat -i L:\Programming\Hercules\mvs-tk5\dasd\tk5002.299 pascal.passamp/pcross:sca>pcross.pas
..\dasdcat -i L:\Programming\Hercules\mvs-tk5\dasd\tk5002.299 pascal.passamp/peditor:sca>peditor.pas
..\dasdcat -i L:\Programming\Hercules\mvs-tk5\dasd\tk5002.299 pascal.passamp/pformat:sca>pformat.pas
..\dasdcat -i L:\Programming\Hercules\mvs-tk5\dasd\tk5002.299 pascal.passamp/pinterp:sca>pinterp.pas
..\dasdcat -i L:\Programming\Hercules\mvs-tk5\dasd\tk5002.299 pascal.passamp/pretty:sca>pretty.pas
..\dasdcat -i L:\Programming\Hercules\mvs-tk5\dasd\tk5002.299 pascal.passamp/printme:sca>printme.pas
..\dasdcat -i L:\Programming\Hercules\mvs-tk5\dasd\tk5002.299 pascal.passamp/profiler:sca>profiler.pas
..\dasdcat -i L:\Programming\Hercules\mvs-tk5\dasd\tk5002.299 pascal.passamp/psubset:sca>psubset.pas
..\dasdcat -i L:\Programming\Hercules\mvs-tk5\dasd\tk5002.299 pascal.passamp/qsort:sca>qsort.pas
..\dasdcat -i L:\Programming\Hercules\mvs-tk5\dasd\tk5002.299 pascal.passamp/rnf:sca>rnf.pas
..\dasdcat -i L:\Programming\Hercules\mvs-tk5\dasd\tk5002.299 pascal.passamp/rnfdoc:sca>rnfdoc.pas
..\dasdcat -i L:\Programming\Hercules\mvs-tk5\dasd\tk5002.299 pascal.passamp/rnfdocin:sca>rnfdocin.pas
..\dasdcat -i L:\Programming\Hercules\mvs-tk5\dasd\tk5002.299 pascal.passamp/snapshot:sca>snapshot.pas
..\dasdcat -i L:\Programming\Hercules\mvs-tk5\dasd\tk5002.299 pascal.passamp/soma:sca>soma.pas
